# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: user/v1/user.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import user.v1.user_pb2 as user_dot_v1_dot_user__pb2


class UserService(Protocol):
    async def create(self, request: user_dot_v1_dot_user__pb2.CreateRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.CreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def read(self, request: user_dot_v1_dot_user__pb2.ReadRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update(self, request: user_dot_v1_dot_user__pb2.UpdateRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.UpdateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete(self, request: user_dot_v1_dot_user__pb2.DeleteRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.DeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceASGIApplication(ConnectASGIApplication[UserService]):
    def __init__(self, service: UserService | AsyncGenerator[UserService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/user.v1.UserService/Create": Endpoint.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.CreateRequest,
                        output=user_dot_v1_dot_user__pb2.CreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create,
                ),
                "/user.v1.UserService/Read": Endpoint.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.ReadRequest,
                        output=user_dot_v1_dot_user__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.read,
                ),
                "/user.v1.UserService/Update": Endpoint.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.UpdateRequest,
                        output=user_dot_v1_dot_user__pb2.UpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update,
                ),
                "/user.v1.UserService/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.DeleteRequest,
                        output=user_dot_v1_dot_user__pb2.DeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/user.v1.UserService"


class UserServiceClient(ConnectClient):
    async def create(
        self,
        request: user_dot_v1_dot_user__pb2.CreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.CreateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.CreateRequest,
                output=user_dot_v1_dot_user__pb2.CreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def read(
        self,
        request: user_dot_v1_dot_user__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.ReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.ReadRequest,
                output=user_dot_v1_dot_user__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update(
        self,
        request: user_dot_v1_dot_user__pb2.UpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.UpdateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.UpdateRequest,
                output=user_dot_v1_dot_user__pb2.UpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: user_dot_v1_dot_user__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.DeleteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.DeleteRequest,
                output=user_dot_v1_dot_user__pb2.DeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class UserServiceSync(Protocol):
    def create(self, request: user_dot_v1_dot_user__pb2.CreateRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.CreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def read(self, request: user_dot_v1_dot_user__pb2.ReadRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.ReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update(self, request: user_dot_v1_dot_user__pb2.UpdateRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.UpdateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete(self, request: user_dot_v1_dot_user__pb2.DeleteRequest, ctx: RequestContext) -> user_dot_v1_dot_user__pb2.DeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class UserServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: UserServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/user.v1.UserService/Create": EndpointSync.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.CreateRequest,
                        output=user_dot_v1_dot_user__pb2.CreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/user.v1.UserService/Read": EndpointSync.unary(
                    method=MethodInfo(
                        name="Read",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.ReadRequest,
                        output=user_dot_v1_dot_user__pb2.ReadResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.read,
                ),
                "/user.v1.UserService/Update": EndpointSync.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.UpdateRequest,
                        output=user_dot_v1_dot_user__pb2.UpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update,
                ),
                "/user.v1.UserService/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="user.v1.UserService",
                        input=user_dot_v1_dot_user__pb2.DeleteRequest,
                        output=user_dot_v1_dot_user__pb2.DeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/user.v1.UserService"


class UserServiceClientSync(ConnectClientSync):
    def create(
        self,
        request: user_dot_v1_dot_user__pb2.CreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.CreateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.CreateRequest,
                output=user_dot_v1_dot_user__pb2.CreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def read(
        self,
        request: user_dot_v1_dot_user__pb2.ReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.ReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Read",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.ReadRequest,
                output=user_dot_v1_dot_user__pb2.ReadResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update(
        self,
        request: user_dot_v1_dot_user__pb2.UpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.UpdateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.UpdateRequest,
                output=user_dot_v1_dot_user__pb2.UpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete(
        self,
        request: user_dot_v1_dot_user__pb2.DeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> user_dot_v1_dot_user__pb2.DeleteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="user.v1.UserService",
                input=user_dot_v1_dot_user__pb2.DeleteRequest,
                output=user_dot_v1_dot_user__pb2.DeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
