# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/v1/user.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\"\x9e\x01\n\x04User\x12\x1c\n\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1e\n\nmiddlename\x18\x02 \x01(\tR\nmiddlename\x12\x1a\n\x08lastname\x18\x03 \x01(\tR\x08lastname\x12\x14\n\x05\x65mail\x18\x04 \x01(\tR\x05\x65mail\x12\x14\n\x05phone\x18\x05 \x01(\tR\x05phone\x12\x10\n\x03\x64ob\x18\x06 \x01(\tR\x03\x64ob\"2\n\rCreateRequest\x12!\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.UserR\x04user\":\n\x0e\x43reateResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\"\x1d\n\x0bReadRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"K\n\x0cReadResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.UserR\x04user\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\"B\n\rUpdateRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12!\n\x04user\x18\x02 \x01(\x0b\x32\r.user.v1.UserR\x04user\"M\n\x0eUpdateResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.UserR\x04user\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\"\x1f\n\rDeleteRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"*\n\x0e\x44\x65leteResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xfb\x01\n\x0bUserService\x12;\n\x06\x43reate\x12\x16.user.v1.CreateRequest\x1a\x17.user.v1.CreateResponse\"\x00\x12\x35\n\x04Read\x12\x14.user.v1.ReadRequest\x1a\x15.user.v1.ReadResponse\"\x00\x12;\n\x06Update\x12\x16.user.v1.UpdateRequest\x1a\x17.user.v1.UpdateResponse\"\x00\x12;\n\x06\x44\x65lete\x12\x16.user.v1.DeleteRequest\x1a\x17.user.v1.DeleteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=32
  _globals['_USER']._serialized_end=190
  _globals['_CREATEREQUEST']._serialized_start=192
  _globals['_CREATEREQUEST']._serialized_end=242
  _globals['_CREATERESPONSE']._serialized_start=244
  _globals['_CREATERESPONSE']._serialized_end=302
  _globals['_READREQUEST']._serialized_start=304
  _globals['_READREQUEST']._serialized_end=333
  _globals['_READRESPONSE']._serialized_start=335
  _globals['_READRESPONSE']._serialized_end=410
  _globals['_UPDATEREQUEST']._serialized_start=412
  _globals['_UPDATEREQUEST']._serialized_end=478
  _globals['_UPDATERESPONSE']._serialized_start=480
  _globals['_UPDATERESPONSE']._serialized_end=557
  _globals['_DELETEREQUEST']._serialized_start=559
  _globals['_DELETEREQUEST']._serialized_end=590
  _globals['_DELETERESPONSE']._serialized_start=592
  _globals['_DELETERESPONSE']._serialized_end=634
  _globals['_USERSERVICE']._serialized_start=637
  _globals['_USERSERVICE']._serialized_end=888
# @@protoc_insertion_point(module_scope)
